name: Capy Content Storage Image

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    name: Build containers
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Preparing buildx
        run: |
          docker run --privileged --rm tonistiigi/binfmt --install arm64
          docker buildx create --use
      - name: Building capy-content-storage images and push to hub
        run: |
          docker buildx build --tag krol44/capy-content-storage:1 \
                              --tag krol44/capy-content-storage:latest \
                              --push --platform linux/amd64,linux/arm64 .